---
- name: EC2 Instance Configration
  hosts: all
  become: true
  gather_facts: false

  vars:
    app_name: "{{ lookup('env', 'APP_NAME') }}"
    app_img: "{{ lookup('env', 'APP_IMG') }}"
    mongo_uri: "{{ lookup('env', 'MONGO_URI') }}"

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Prepare Docker
      block:
        - name: Check if Docker is installed
          command: docker --version
          register: docker_installed
          ignore_errors: true

        - name: Install Docker on Debian/Ubuntu
          apt:
            name: docker.io
            state: present
          when: docker_installed.rc != 0
          tags: docker

        - name: Start Docker service
          service:
            name: docker
            state: started
            enabled: yes
          when: docker_installed.rc != 0
          tags: docker        

        - name: Create Docker container if it does not exist
          docker_container:
            name: "{{ app_name }}"
            image: "{{ app_img }}" # img:tag
            state: started
            recreate: true
            restart_policy: unless-stopped
            ports:
              - "3000:3000"
            env:
              MONGO_URI: "{{ mongo_uri }}"
