pipeline{
    agent any
    tools{
        nodejs "node"
    }
    stages{
        stage("build"){
            steps{
                echo "========unit-test========"
                sh "cd ahmed"
                sh "npm test"
            }
        }
        stage("code-coverage"){
            steps{
                echo "========code-coverage========"
                sh "npm run coverage"
            }
        }
        stage("starting"){
            steps{
                echo "========starting-app========"
                sh "npm start"
            }
        }
    }
            
}
