pipeline{
    agent any
    tools{
        nodejs "node"
    }
    stages{
        stage("build"){
            steps{
                echo "========unit-test========"
                sh "npm --prefix /var/lib/jenkins/workspace/ahmed-pipeline/ahmed test"
            }
        }
        stage("code-coverage"){
            steps{
                echo "========code-coverage========"
                sh "npm --prefix /var/lib/jenkins/workspace/ahmed-pipeline/ahmed run coverage"
            }
        }
        stage("starting"){
            steps{
                echo "========starting-app========"
                sh "npm --prefix /var/lib/jenkins/workspace/ahmed-pipeline/ahmed start"
            }
        }
    }
            
}
